accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.login, name="login_user"),
    path("dashboard", views.index, name="dashboard"),
    path('logout', views.logout, name='logout_user'),
    path("register", views.register, name="register_user"),
    path("reset_password", views.reset_password, name="reset_password"),
    path("settings", views.settings, name="settings"),
    path("forgot_password", views.forgot_password, name="forgot_password"),
    
]

esecurify_frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("accounts.urls"))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_number = models.CharField(max_length=15)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

accounts/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout, update_session_auth_hash
from django.shortcuts import render
from django.contrib.auth.models import User
from accounts.models import UserProfile
from django.urls import reverse


def index(request):
    return render(request, "dashboard.html")

def login(request):
    if request.method == 'POST':
        user_data = request.POST
        email = user_data['email']
        password = user_data['password']
        user = authenticate(request, username=email, password=password)
        
        if not user or user.userprofile.is_deleted:
            print("Hello")
            
            return render(request, 'login.html', {'error': 'Invalid username or password!'})
        auth_login(request, user)
        
        return JsonResponse({
            "retcode": 1
        })
        
    else:
        user = request.user
        if not user.is_authenticated:
            return render(request, 'login.html')
    return HttpResponseRedirect(reverse('accounts:dashboard'))


    
    return render(request, "login.html")

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('accounts:login_user'))

def register(request):
    if request.method == 'POST':
        user_data = request.POST
        first_name = user_data['first-name']
        last_name = user_data['last-name']
        email = user_data['email']
        password = user_data['password']
        confirm_password = user_data['confirm-password']
        if password == confirm_password:
            user = User.objects.create_user(
                first_name = first_name,
                last_name = last_name,
                email = email,
                username = email,
                password = password,
            )
            UserProfile(
                user = user
            ).save()
            return JsonResponse({"retcode":1})
        else:
            return JsonResponse({"retcode":0})
    return render(request, "register.html")

def forgot_password(request):
    return render(request, "forgot_password.html")
    
def reset_password(request):
    pass

def settings(request):
    return render(request,'settings.html')

accounts/templates/dashboard.html
{% extends 'base.html' %}
{% block content_title %}Dashboard{% endblock %}
{% block breadcrumbs %}
    <span class="h-20px border-gray-200 border-start mx-4"></span>
    <ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
        <li class="breadcrumb-item text-muted">
            Dashboard
        </li>
    </ul>
{% endblock %}
{% block content %}
<div class="card mb-5 mb-xl-10">
    <div class="card-body pt-9 pb-0">
        <div class="d-flex flex-wrap flex-sm-nowrap mb-3">
            <div class="me-7 mb-4">
                <h1>Welcomr to Dashboard</h1>

            </div>
        </div>
        
    </div>
</div>
{% endblock %}

accounts/templates/forgot_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>eSecurify | We Rainforce Security!</title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta charset="utf-8" />
		<link rel="shortcut icon" href="{% static 'media/logos/favicon.png' %}" />
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
        <link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
	</head>
	<body id="kt_body" class="bg-body">
		<div class="d-flex flex-column flex-root">
			<div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed" style="background-image: url(static/media/illustrations/development-hd.png)">
				<div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
					<a href="{% url 'accounts:forgot_password' %}" class="mb-12">
						<img alt="Logo" src="{% static 'media/logos/logo.png' %}" class="h-45px" />
					</a>
					<div class="w-lg-500px bg-body rounded shadow-sm p-10 p-lg-15 mx-auto">
						<form class="form w-100" novalidate="novalidate" id="kt_password_reset_form">
							<div class="text-center mb-10">
								<h1 class="text-dark mb-3">Forgot Password ?</h1>
								<div class="text-gray-400 fw-bold fs-4">Enter your email to reset your password.</div>
							</div>
							<div class="fv-row mb-10">
								<label class="form-label fw-bolder text-gray-900 fs-6">Email</label>
								<input class="form-control form-control-solid" type="email" placeholder="" name="email" autocomplete="off" />
							</div>
							<div class="d-flex flex-wrap justify-content-center pb-lg-0">
								<button type="button" id="kt_password_reset_submit" class="btn btn-lg btn-primary fw-bolder me-4">
									<span class="indicator-label">Submit</span>
									<span class="indicator-progress">Please wait...
									<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
								</button>
								<a href="../../demo1/dist/authentication/flows/basic/sign-up.html" class="btn btn-lg btn-light-primary fw-bolder">Cancel</a>
							</div>
						</form>
					</div>
				</div>
				<div class="d-flex flex-center flex-column-auto p-10">
					<div class="d-flex align-items-center fw-bold fs-6">
						<a href="https://keenthemes.com" class="text-muted text-hover-primary px-2">About</a>
						<a href="mailto:support@keenthemes.com" class="text-muted text-hover-primary px-2">Contact</a>
						<a href="https://1.envato.market/EA4JP" class="text-muted text-hover-primary px-2">Contact Us</a>
					</div>
				</div>
			</div>
		</div>
        <script src="{% static 'plugins/global/plugins.bundle.js' %}" src="assets/"></script>
		<script src="{% static 'js/scripts.bundle.js' %}"></script>
        <script src="{% static 'js/custom/authentication/password-reset/password-reset.js' %}"></script>
	</body>
</html>

accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>eSecurify | We Rainforce Security!</title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta charset="utf-8" />
		<link rel="shortcut icon" href="{% static 'media/logos/favicon.png' %}" />
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
		<link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
	</head>
	<body id="kt_body" class="bg-body">
		<div class="d-flex flex-column flex-root">
			<div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed" style="background-image: url(static/media/illustrations/development-hd.png)">
				<div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
					<a href="{% url 'accounts:login_user' %}" class="mb-12">
						<img alt="Logo" src="{% static 'media/logos/logo.png' %}" class="h-45px" />
					</a>

					<div class="w-lg-500px bg-body rounded shadow-sm p-10 p-lg-15 mx-auto">
						<form class="form w-100" novalidate="novalidate" id="sign_in_form" action="#">
							{% csrf_token %}

							<div class="text-center mb-10">
								<h1 class="text-dark mb-3">Sign In to eSecurify</h1>
								<div class="text-gray-400 fw-bold fs-4">New Here?
								<a href="{% url 'accounts:register_user' %}" class="link-primary fw-bolder">Create an Account</a></div>
							</div>

                            <div class="d-flex align-items-center mb-10">
                                <div class="border-bottom border-gray-300 mw-50 w-100">

                                </div>
                                <div class="border-bottom border-gray-300 mw-50 w-100">

                                </div>
                            </div>

							<div class="fv-row mb-10">
								<label class="form-label fs-6 fw-bolder text-dark">Email</label>
								<input placeholder="Email" class="form-control form-control-lg form-control-solid" type="text" name="email" autocomplete="off" />
							</div>

							<div class="fv-row mb-10">
								<div class="d-flex flex-stack mb-2">
									<label class="form-label fw-bolder text-dark fs-6 mb-0">Password</label>
									<a href="{% url 'accounts:forgot_password' %}" class="link-primary fs-6 fw-bolder">Forgot Password ?</a>
								</div>
								<input placeholder="Password" class="form-control form-control-lg form-control-solid" type="password" name="password" autocomplete="off" />
							</div>

							<div class="text-center">
								<button type="submit" id="sign_in_submit" class="btn btn-lg btn-primary w-100 mb-5">
									<span class="indicator-label">Continue</span>
									<span class="indicator-progress">Please wait...
									<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
								</button>
							</div>

						</form>
					</div>
				</div>

				<div class="d-flex flex-center flex-column-auto p-10">
					<div class="d-flex align-items-center fw-bold fs-6">
						<a href="https://www.esecurify.com/" class="text-muted text-hover-primary px-2">Home</a>
						<a href="https://www.esecurify.com/#section-services" class="text-muted text-hover-primary px-2">Service</a>
						<a href="https://www.esecurify.com/#section-contact-us" class="text-muted text-hover-primary px-2">Contact Us</a>
					</div>
				</div>

			</div>
		</div>

		<script src="{% static 'plugins/global/plugins.bundle.js' %}" src="assets/"></script>
		<script src="{% static 'js/scripts.bundle.js' %}"></script>
		<!-- <script src="{% static 'js/custom/authentication/sign-in/general.js' %}"></script> -->

	</body>
</html>

<script>
	"use strict";
	function handleFormSubmit(){
		const form = document.querySelector("#sign_in_form");
		const submitButton = document.querySelector("#sign_in_submit");
		let validator = FormValidation.formValidation(form,{
			fields:{
				email: {
                    validators: {
                        notEmpty: {
                            message: "Email address is required"
                        },
                        emailAddress: {
                            message: "The value is not a valid email address",
                        },
                    },
                },
				password: {
                    validators: {
                        notEmpty: {
                            message: "The password is required"
                        },
                        callback: {
                            message: "Please enter valid password",
                            callback: function (e) {
                                if (e.value.length > 0) return r();
                            },
                        },
                    },
                },
			},
			plugins:{
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap: new FormValidation.plugins.Bootstrap5({
					rowSelector: ".fv-row",
				}),
			},
		});
		submitButton.addEventListener("click", function(n){
			n.preventDefault();
			validator.validate().then(function(val){
				"Valid" == val ? (submitButton.setAttribute("data-kt-indicator", "on"),
				(submitButton.disabled = !0),
				setTimeout(function(){
					submitButton.removeAttribute("data-kt-indicator"),
					(submitButton.disabled = !1),
					$.ajax({
						type: "POST",
                        url: "{% url 'accounts:login_user' %}",
                        data: $(form).serialize(),
						success: function(response){
							if (response['retcode']=== 1){
								window.location = "{% url 'accounts:dashboard' %}";
							}
						},
						error: function (jqXHR, textStatus, errorThrown) {
                            alert("Error! Retry, or contact support.");
                        },

					})

				}, 2e3)
				):
				Swal.fire({
                    text: "Sorry, looks like there are some errors detected, please try again.",
                    icon: "error",
                    buttonsStyling: !1,
                    confirmButtonText: "Ok, got it!",
                    customClass: { confirmButton: "btn btn-primary" },
                });
			})
		})
	}

	KTUtil.onDOMContentLoaded(function () {
		handleFormSubmit();
	});
</script>

accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>eSecurify | We Rainforce Security!</title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta charset="utf-8" />
		<link rel="shortcut icon" href="{% static 'media/logos/favicon.png' %}" />
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
        <link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
	</head>
	<body id="kt_body" class="bg-body">
		<div class="d-flex flex-column flex-root">
			<div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed" style="background-image: url(static/media/illustrations/development-hd.png)">
				<div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
					<a href="{% url 'accounts:register_user' %}" class="mb-12">
						<img alt="Logo" src="{% static 'media/logos/logo.png' %}" class="h-45px" />
					</a>
					<div class="w-lg-500px bg-body rounded shadow-sm p-10 p-lg-15 mx-auto">
						<form class="form w-100" novalidate="novalidate" id="sign_up_form">
							{% csrf_token %}
							<div class="mb-10 text-center">
								<h1 class="text-dark mb-3">Create an Account</h1>
								<div class="text-gray-400 fw-bold fs-4">Already have an account?
								<a href="{% url 'accounts:login_user' %}" class="link-primary fw-bolder">Forgot Password ?</a></div>
							</div>
                            <div class="d-flex align-items-center mb-10">
                                <div class="border-bottom border-gray-300 mw-50 w-100">

                                </div>
                                <div class="border-bottom border-gray-300 mw-50 w-100">

                                </div>
                            </div>
							<div class="row fv-row mb-7">
								<div class="col-xl-6">
									<label class="form-label fw-bolder text-dark fs-6">First Name</label>
									<input placeholder="First Name" class="form-control form-control-lg form-control-solid" type="text" placeholder="" name="first-name" autocomplete="off" />
								</div>
								<div class="col-xl-6">
									<label class="form-label fw-bolder text-dark fs-6">Last Name</label>
									<input placeholder="Last Name" class="form-control form-control-lg form-control-solid" type="text" placeholder="" name="last-name" autocomplete="off" />
								</div>
							</div>
							<div class="fv-row mb-7">
								<label class="form-label fw-bolder text-dark fs-6">Email</label>
								<input placeholder="Email" class="form-control form-control-lg form-control-solid" type="email" placeholder="" name="email" autocomplete="off" />
							</div>
							<div class="mb-10 fv-row" data-kt-password-meter="true">
								<div class="mb-1">
									<label class="form-label fw-bolder text-dark fs-6">Password</label>
									<div class="position-relative mb-3">
										<input placeholder="Password" class="form-control form-control-lg form-control-solid" type="password" placeholder="" name="password" autocomplete="off" />
										<span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2" data-kt-password-meter-control="visibility">
											<i class="bi bi-eye-slash fs-2"></i>
											<i class="bi bi-eye fs-2 d-none"></i>
										</span>
									</div>
									<div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
										<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
										<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
										<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
										<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
									</div>
								</div>
								<div class="text-muted">Use 8 or more characters with a mix of letters, numbers &amp; symbols.</div>
							</div>
							<div class="fv-row mb-5">
								<label class="form-label fw-bolder text-dark fs-6">Confirm Password</label>
								<input placeholder="Password confirmation" class="form-control form-control-lg form-control-solid" type="password" placeholder="" name="confirm-password" autocomplete="off" />
							</div>
							<div class="fv-row mb-10">
								<label class="form-check form-check-custom form-check-solid form-check-inline">
									<input class="form-check-input" type="checkbox" name="toc" value="1" />
									<span class="form-check-label fw-bold text-gray-700 fs-6">I Agree
									<a href="#" class="ms-1 link-primary">Terms and conditions</a>.</span>
								</label>
							</div>
							<div class="text-center">
								<button type="button" id="sign_up_submit" class="btn btn-lg btn-primary w-100 mb-5">
									<span class="indicator-label">Submit</span>
									<span class="indicator-progress">Please wait...
									<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
								</button>
                                <a href="{% url 'accounts:login_user' %}">
                                    <button type="button" id="" class="btn btn-lg btn-light-primary w-100 mb-5">
                                        Cancel
                                    </button>
                                </a>
							</div>
						</form>
					</div>
				</div>
				<div class="d-flex flex-center flex-column-auto p-10">
					<div class="d-flex align-items-center fw-bold fs-6">
						<a href="https://www.esecurify.com/" class="text-muted text-hover-primary px-2">Home</a>
						<a href="https://www.esecurify.com/#section-services" class="text-muted text-hover-primary px-2">Service</a>
						<a href="https://www.esecurify.com/#section-contact-us" class="text-muted text-hover-primary px-2">Contact Us</a>
					</div>
				</div>
			</div>
		</div>
		
        <script src="{% static 'plugins/global/plugins.bundle.js' %}" src="assets/"></script>
		<script src="{% static 'js/scripts.bundle.js' %}"></script>
		<!-- <script src="{% static 'js/custom/authentication/sign-up/general.js' %}"></script> -->

	</body>
</html>

<script>
    "use strict";
    function handleSubmitForm(){
        const form = document.querySelector("#sign_up_form");
        const submitButton = document.querySelector("#sign_up_submit");
        const passwordMeter = KTPasswordMeter.getInstance(form.querySelector('[data-kt-password-meter="true"]'));
        let validator = FormValidation.formValidation(form,{
            fields :{
                "first-name": {
                    validators: {
                        notEmpty: {
                            message: "First Name is required"
                        }
                    },
                },
                "last-name": {
                    validators: {
                        notEmpty: {
                            message: "Last Name is required"
                        }
                    },
                },
                email: {
                    validators: {
                        notEmpty: {
                            message: "Email address is required"
                        },
                        emailAddress: {
                            message: "The value is not a valid email address",
                        },
                    },
                },
                password: {
                    validators: {
                        notEmpty: {
                            message: "The password is required"
                        },
                        callback: {
                            message: "Please enter valid password",
                            callback: function (e) {
                                if (e.value.length > 0) return r();
                            },
                        },
                    },
                },
                "confirm-password": {
                    validators: {
                        notEmpty: {
                            message: "The password confirmation is required"
                        },
                        identical: {
                            compare: function () {
                                return form.querySelector('[name="password"]').value;
                            },
                            message: "The password and its confirm are not the same",
                        },
                    },
                },
                toc: {
                    validators: {
                        notEmpty: {
                            message: "You must accept the terms and conditions",
                        },
                    },
                },
            },
            plugins:{
                trigger: new FormValidation.plugins.Trigger({
                    event: { password: !1 },
                }),
                bootstrap: new FormValidation.plugins.Bootstrap5({
                    rowSelector: ".fv-row",
                    eleInvalidClass: "",
                    eleValidClass: "",
                }),
            }
        });
        submitButton.addEventListener("click", function(r){
            r.preventDefault(),
            validator.revalidateField("password"),
            validator.validate().then(function(val){
                "Valid" == val ? (submitButton.setAttribute("data-kt-indicator", "on"),
                (submitButton.disabled = !0),
                setTimeout(function(){
                    submitButton.removeAttribute("data-kt-indicator"),
                    (submitButton.disabled = !1),
                    $.ajax({
                        type: "POST",
                        url: "{% url 'accounts:register_user' %}",
                        data: $(form).serialize(),
                        dataType: "json",
                        success: function(response){
                            Swal.fire({
                                text: "Thanks for register..!",
                                icon: "success",
                                buttonsStyling: !1,
                                confirmButtonText: "Ok, got it!",
                                customClass: {
                                    confirmButton: "btn btn-primary"
                                },
                            }).then(function(t){
                                t.isConfirmed && (form.reset());
								window.location = "{% url 'accounts:login_user' %}";
                            });
                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                            alert("Error! Retry, or contact support.");
                        },
                    })
                }, 1500))
                : Swal.fire({
                    text: "Sorry, looks like there are some errors detected, please try again.",
                    icon: "error",
                    buttonsStyling: !1,
                    confirmButtonText: "Ok, got it!",
                    customClass: { confirmButton: "btn btn-primary" },
                });
            })
        }),
        form.querySelector('input[name="password"]').addEventListener("input", function(){
            this.value.length > 0 && validator.updateFieldStatus("password", "NotValidated");
        });
    }

    KTUtil.onDOMContentLoaded(function () {
        handleSubmitForm();
    });
</script>